Feature/signup page
frontendcafe/cmyk-night pull request #17
Opened 2021-05-04 17:10 UTC by AnibalDBXD

Desktop: 
![desktop](https://user-images.githubusercontent.com/66853369/117042553-221b6200-acda-11eb-9604-795f6f7e9bf8.JPG)

Mobile: 
![mobile](https://user-images.githubusercontent.com/66853369/117042562-247dbc00-acda-11eb-8992-2175ab604b8f.JPG)

2021-05-04 22:48 UTC, JorgeJOcampo requested changes

2021-05-04 22:48 UTC, JorgeJOcampo commented on src/components/Input.js
> +                <input className="InputContainer__input" autoComplete={autoComplete} type={password ? "password": "email"} placeholder={name} />
Para el registro no funciona el type={password ? "password": "email"} xq justamente no hay password. Además si querés que sea reutilizable este componente, sería mejor tener un prop type y usarlo en cada lugar donde lo uses. Además que es más legible por fuera.

2021-05-04 22:48 UTC, JorgeJOcampo commented on src/components/Input.js
> +    if(newPassword) autoComplete = "new-password"
autocomplete sólo puede ser on|off, ésto no haría nada. Plus, está on por default. Si querías especificar con qué prop buscar el autocomplete, es con id o name. Te dejo la doc para más info.
https://www.w3schools.com/tags/att_input_autocomplete.asp

2021-05-04 22:48 UTC, JorgeJOcampo commented on src/pages/Login.js
> +import "./style/Login&SignUp.css";
En general, no es muy conveniente que uses caracteres especiales como &, podrían llegar a dar algún problema con alguna lib o webpack en algún momento

2021-05-04 23:28 UTC, AnibalDBXD commented on src/components/Input.js
> +    if(newPassword) autoComplete = "new-password"
Tienes razon y yo tambien creo que es asi pero me fije en la consola y me mostro esto y lo coloque, igual hare como dices
![image](https://user-images.githubusercontent.com/66853369/117081842-c0291f80-ad0e-11eb-8c2c-0d42c2bedc33.png)

2021-05-06 22:26 UTC, JorgeJOcampo approved these changes

2021-05-06 22:26 UTC, merged